### ISSUE TITLE
Feature List Improvements

### ISSUE THREAD

**Issue by idbentley** [COrtaDev/Dizney-Plus#1]
Hello Disney+ Team!

After reviewing your feature list documentation, here is a list of our feedback. Please address these concerns today (Thursday July 9) and send a message in your slack channel when addressed.
 - In general these features leave too much to interpretation - add a lot of details about what actions a user can take, and what authorizations are needed to do so.  Instead of "User Auth" specify each of the features needed: "User login, signup, profile page, etc."
 - How will the catalogue be searchable?  By Genre, Type, Family Friendly, Popular, etc.
 - Make watch list required and support all four CRUD operations for creating new lists.  Also support CRUD operations for adding to and modifying these watch lists.
 - Likes/Ratings should support all four CRUD operations
 - User Profile page should act as a view for watch lists and likes/ratings
 - Add Heroku hosting of site and database as feature
 - Add high quality README.md and documentation as feature
 - Add one or two Bonus / Stretch goals that you will implement if you have time.

Because your feature list is somewhat sparse, you should call a TA to do final review as soon as practical.

**Comment by brandonheld** [comment]
Feature List was reviewed and improved upon.
