### ISSUE TITLE
Routes Improvements

### ISSUE THREAD

**Issue by idbentley** [COrtaDev/Dizney-Plus#2]
- `/home` ought to be just `/`
 - `/search` doesn't need a `GET` - the search form appears as a dynamic element, rather than a full page.
 - `/search` queries should use a `POST` method rather than `PATCH`.
 - You should add a route `POST /watchlist/add/:showId` to add a new show to the current Profile's watchlist.
 - `GET /watchlist/:id` the id here can be left out `GET /watchlist` and always use the current Profile's watchlist.
 - `DELETE /watchlist/:showId` instead of `DESTROY /movies/:id`  This way, you use one endpoint for both movies' and for series'.
 - Add user interaction routes for signup, login, etc.
 - `/select-avatar` ought to be a `PATCH /users/profiles/`  with the form being on `GET /users/profiles/edit`
 - Make `profile` routes RESTful: For example: `GET /add-profile` should be: `GET /users/profiles/new` `GET /select-profile` should be: `GET /users/profiles`.
 - Remove `GET /edit-profiles` route, there should be links on the `GET /users/profiles` page to DELETE a specific profile.
 - What is `Brands` and is that related to `Collections`?   What routes are needed for collections?

**Comment by brandonheld** [comment]
Routes reviewed and edited.
